# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 04:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurants_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restaurants',
            new_name='RestaurantsLocations',
        ),
    ]
