# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 04:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_restaurantslocations_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantslocations',
            name='timestemp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurantslocations',
            name='updateTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
