# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 04:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_auto_20171127_0445'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantslocations',
            name='upload',
            field=models.FileField(default=django.utils.timezone.now, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
