# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 05:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_restaurantslocations_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantslocations',
            name='upload',
        ),
    ]
