# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 23:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_remove_restaurantslocations_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantslocations',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
