# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_restaurantslocations_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantslocations',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
