# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 23:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_auto_20171127_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantslocations',
            name='slug',
        ),
    ]
