# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0014_auto_20171201_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantslocations',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
