# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 06:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0015_auto_20171201_0612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantslocations',
            old_name='timestemp',
            new_name='timestamp',
        ),
    ]
